version: '3'

services:
  twitter-kafka-producer:
    hostname: twitter-kafka-producer
    container_name: twitter-kafka-producer
    image: twitter-kafka-producer:latest

  sentiment-analyser:
    hostname: sentiment-analyser
    container_name: sentiment-analyser
    image: sentiment-analyser:latest
    ports: 
      - 3000:3000